!VSETextEncoder
metas:
  py_modules:
    - vocab.py
    - model.py
    - __init__.py
requests:
  on:
    IndexRequest:
      - !FilterQL
        with:
          lookups: {'modality': 'text'}
      - !EncodeDriver {}
    SearchRequest:
      - !FilterQL
        with:
          lookups: {'mime_type__contains': 'text'}
      - !EncodeDriver {}
